### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by thejordanwood**
@dmundra 

- I'd like to rename this page from VPAT to Accessibility Conformance Report (ACR). What is the best way to do that?
- I also have a meta description for this page, but am not sure where it goes. Description: "Learn how an ACR can improve your procurement process."
- Right now the heading of the page shows up twice. Is there a way to correct that?

### CODE REVIEW

**Comment by dmundra** [comment]
@thejordanwood I believe if you add the following block of text to the top the page it will do all your requests:

```
---
title: Accessibility Conformance Report (ACR)
description: Guidance for prioritizing accessibility bugs based on degree of user impact on top tasks 
---
```

Then remove the title `# Accessibility Conformance Report (ACR)` from the page. Try that and let's see if it works.

**Review by dmundra — APPROVED** [review]

**Comment by thejordanwood** [comment]
@dmundra I think something happened here. The [original VPAT](https://accessibility.civicactions.com/VPAT/) link now shows a 404. 

Now that I think about it, the new link should probably be https://accessibility.civicactions.com/ACR/ and /VPAT should redirect there.

**Comment by dmundra** [comment]
Ah good catch @thejordanwood I can fix those. It appears that https://accessibility.civicactions.com/VPAT/ goes to a 404 but https://accessibility.civicactions.com/VPAT goes to the page. I will try to have both go to /ACR/

**Comment by thejordanwood** [comment]
@dmundra It also looks like "Learn how an Accessibility Conformance Report (ACR) can improve your procurement process." appears on the page, when I meant for that to just be a meta description that doesn't show on the front end. Do you want me to open a new PR to fix that?

**Comment by dmundra** [comment]
> @dmundra It also looks like "Learn how an Accessibility Conformance Report (ACR) can improve your procurement process." appears on the page, when I meant for that to just be a meta description that doesn't show on the front end. Do you want me to open a new PR to fix that?

Ah I just noticed that. I think that is a feature of the layout. I can try a different layout and see if it removes it from the page. Sorry about that.

**Comment by thejordanwood** [comment]
@dmundra No problem! If the different layout doesn't work, then we can just remove that line.

**Pull request merged**
