### PR TITLE
Retext blog post

### LINKED ISSUE #268: Blog post on use of retext
Similar to: https://accessibility.civicactions.com/posts/automated-accessibility-testing-leveraging-github-actions-and-pa11y-ci-with-axe

cc @dmundra @mgifford

### PR DESCRIPTION
**Pull request by dmundra**
Closes #268

### CODE REVIEW

**Comment by lukefretwell** [comment]
@dmundra is the Google doc still the best place to review and finalize this?

**Comment by dmundra** [comment]
> @dmundra is the Google doc still the best place to review and finalize this?

Yes @lukefretwell

**Comment by lukefretwell** [comment]
@dmundra both @Marlena-Medford and I are done, so ready to publish! 🚀

**Comment by dmundra** [comment]
Thanks, @lukefretwell. This PR is ready for review.

**Review by lukefretwell — APPROVED** [review]

**Pull request merged**
