### PR TITLE
Update and rename ux-designer.md to designer.md

### PR DESCRIPTION
**Pull request by thejordanwood**
@dmundra I'd like to remove all of the accordions and add this content onto the page. This is how we want to structure the roles pages moving forward. I'm not seeing where the accordions are controlled though?

### CODE REVIEW

**Review by dmundra — COMMENTED** [review]
@thejordanwood the accordions are generated dynamically. I am not sure how this new page will look but lets preview it. You can do that by adding the label 'qa-pull-request' to this pull request. Once that job finishes it will provide a comment with a URL to the QA site.

**Comment by thejordanwood** [comment]
@dmundra I have managed to 404 the [original ux designer page](https://accessibility-qa.civicactions.com/roles/ux-designer) and the [new designer page](https://accessibility-qa.civicactions.com/roles/designer) shows no content at all, so I guess that wasn't the way to do things. What would be a better way to handle this?

**Comment by dmundra** [comment]
> @dmundra I have managed to 404 the [original ux designer page](https://accessibility-qa.civicactions.com/roles/ux-designer) and the [new designer page](https://accessibility-qa.civicactions.com/roles/designer) shows no content at all, so I guess that wasn't the way to do things. What would be a better way to handle this?

Ya I figured that might happen. I think I can figure out how to get your page going but it will take me a little bit to investigate. Can we leave this up while I try that?

**Comment by thejordanwood** [comment]
@dmundra Yep! There's no rush on this, so take your time. Thanks for looking into it.

**Comment by dmundra** [comment]
@thejordanwood so I was to able to make your role page act like a guide page by adding the following:

* A new layout option called 'role-default' that won't add accordions. I set that as the layout for the designer page.
* I added 'redirect_from' to redirect the old /roles/ux-designer page to the new one.
* Some additions I made was also to update the roles landing page to link to the new page and update the roles pages to show other role links in the sidebar.

**Review by dmundra — COMMENTED** [review]
@thejordanwood review the page now https://accessibility-qa.civicactions.com/roles/designer. How is that looking?

**Comment by dmundra** [comment]
@laflannery since I added a bunch of changes can you review this PR or @maggiewachs? Let me know if you have any questions.

**Comment by thejordanwood** [comment]
@dmundra Thanks for figuring that out! The page looks great to me. Can we also get rid of the Content Designer page and redirect to the Designer page? The UX and Content designer pages are being combined into this one. 

cc: @laflannery

**Comment by dmundra** [comment]
> @dmundra Thanks for figuring that out! The page looks great to me. Can we also get rid of the Content Designer page and redirect to the Designer page? The UX and Content designer pages are being combined into this one.
> 
> cc: @laflannery

@thejordanwood yes I can do that.

**Review by laflannery — APPROVED** [review]

**Pull request merged**
