### PR TITLE
Pa11y automated testing

### LINKED ISSUE #52: Setup automated accessibility testing for the accessibility site
Related to #39, we should set up automated accessibility tests against https://civicactions.github.io/accessibility/.

### PR DESCRIPTION
**Pull request by dmundra**
This request will merge a GitHub action that will start up a local version of the accessibility site and test the pages for WCAG2AA accessibility issues. Example of the action being run in my fork: https://github.com/dmundra/accessibility/actions?query=workflow%3A%22pa11y+tests%22

A brief overview of files and changes:
* .github/workflows/README.md: Readme file explaining the action and the report it generates. Also provides instructions on how to run it locally.
* .github/workflows/pa11y.yml: The GitHub action file which will run the pa11y-ci tool against the local version of the site.
* .gitignore: Ignore some of the artifacts generated by the action.
* .pa11yci: Configuration file for pa11y-ci.
* .pa11yci_with_axe: Configuration file with 'axe' runner (this currently reports a lot of accessibility errors so skipping for now)
* Changes to site files including VPAT: Fixed accessibility issues reported by pa11y-ci to get the action to pass.
* package.json and package-lock.json: Added pa11y-ci dependencies to the project and added custom commands that are used by the action to trigger pa11y-ci and generate the HTML output.

Please add any questions and comments.

Fixes #52

### CODE REVIEW

**Review by mgifford — APPROVED** [review]
Might have been better to submit the id="main-content" changes separately. I worry that they might be there for the "skip navigation" function. 

Anyways, I'm find implementing this and if we need to add them back later, then no problem.

**Comment by dmundra** [comment]
I wanted to but I didn't want to introduce a failing pipeline so I fixed it. I did test the skipnavs to make sure we didn't remove them. I think the issue was caused by copy-pasting the ``<main...>`` code from the default to other layout files.

Thank you for reviewing and merging this! The pipeline is now live: https://github.com/CivicActions/accessibility/actions?query=workflow%3A%22pa11y+tests%22

**Comment by mgifford** [comment]
That totally makes sense.  Thanks for explaining it.

Does this just run nightly?  Is it on a PR that this will flag errors?  How do we monitor this.

**Comment by dmundra** [comment]
The action will run on every push. Right now it will pass when there are no errors. If they are errors it will fail and you have to navigate to the pipeline to download the reports.

If we do implement a PR workflow then we can switch it to only run on PR and we can publish the errors in the pull request thread. I think that would be good next steps.

What do you think @mgifford?

**Comment by mgifford** [comment]
This sounds great to me.  Thanks.

**Pull request merged**
