### PR TITLE
Retext feature

### LINKED ISSUE #89: Add retextjs to help review content
The CA handbook is reviewing it's content with:
https://github.com/CivicActions/handbook/blob/master/lint/config/retext.problem.js
https://github.com/CivicActions/handbook/blob/master/lint/config/retext.suggestion.js

Might make sense to extend this to look at readability:
https://github.com/retextjs/retext-readability

Would also be great to systemically check for ableist (and other elitist) language by using their equality plugin:
https://github.com/retextjs/retext-equality/

### PR DESCRIPTION
**Pull request by dmundra**
This request will merge a GitHub action retext feature from the handbook site (https://github.com/CivicActions/handbook/pull/697) for the accessibility site. The action will check pull requests for text issues including readability and equality.

The changes are the same as the handbook except for which folders to monitor.

Fixes #89

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford these changes will test accessibility sites changes for readability and equality (plus others that the handbook was testing). Like the handbook, this will only run on pull requests. This will allow for an easier location for changes and their issues to be reviewed.

Do you think it is time we do only make changes via pull requests instead of editing the main branch directly? What do you think?

**Comment by dmundra** [comment]
@grugnog I presume it was okay to copy the handbook reviewdog features you added. Any gotchas we should look out for?

**Comment by grugnog** [comment]
@dmundra this looks great! Happy you were able to make it work :)
I actually started out with these as a separate repo, but I think the config for this is always pretty context sensitive and it wasn't obvious where to draw the line between the action and the config so I kept it all local for now. Perhaps we can see how this works and perhaps look at splitting it out at some point in the future :)

**Review by mgifford — COMMENTED** [review]
Much of this is beyond my experience. Looks good though. The one think I would change is that the agile.md change probably should have been done in another commit. That said, it totally makes sense. No reason to re-do it.

**Comment by dmundra** [comment]
> @dmundra this looks great! Happy you were able to make it work :)
> I actually started out with these as a separate repo, but I think the config for this is always pretty context sensitive and it wasn't obvious where to draw the line between the action and the config so I kept it all local for now. Perhaps we can see how this works and perhaps look at splitting it out at some point in the future :)

Thanks, @grugnog, and agreed. The only changes I made were context related so that makes sense. Maybe it could be a set of parameters passed to the script.

> Much of this is beyond my experience. Looks good though. The one think I would change is that the agile.md change probably should have been done in another commit. That said, it totally makes sense. No reason to re-do it.

Thanks, @mgifford. I wanted to test changes so two birds with one stone. I will rebase it and merge it.

**Pull request merged**
