### PR TITLE
Create accordion.test.js

### PR DESCRIPTION
**Pull request by dmundra**
Added accordion tests.

@jaube05 targetting your branch.

### CODE REVIEW

**Comment by mgifford** [comment]
You are just adding test for the accordion so there is no need to find a URL and test it here https://accessibility-qa.civicactions.com/playbook/ I assume.  I'm going to mark this as approved.

**Review by mgifford — APPROVED** [review]
Thanks for adding the accordion tests. This will be useful as we start having more of them.

**Comment by dmundra** [comment]
Thanks, @mgifford. I am also targetting @jaube05 branch which has the accordion feature in it. I am going to also let her review this one as well and merge it when she is back and working on it.

**Review by jaube05 — APPROVED** [review]
Updated branch, after accordion was merged to main. Tests are good. Thanks @dmundra

**Pull request merged**
