### PR TITLE
Pa11y with axe

### PR DESCRIPTION
**Pull request by dmundra**
Implementing Axe runner for pa11y. Likely a lot of errors so something to review before merging.

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford and @lukefretwell do we want to fix the site to be compatible with Axe? Outside of the VPAT the common issues for all the pages are:

* Double instances of <main>
* Sidebar missing <li>

The rest are heading issues and some other one of problems and then VPAT with its own list of issues.

**Comment by mgifford** [comment]
Yes, we should make sure that it complies with axe testing @dmundra

**Comment by mgifford** [comment]
Here are some of the errors I got from doing a sitewide crawl. Most will be caught by the two PR's I submitted. 

[purple-hats-report.html.zip](https://github.com/CivicActions/accessibility/files/6065458/purple-hats-report.html.zip)

**Comment by dmundra** [comment]
> Yes, we should make sure that it complies with axe testing @dmundra

Thanks, @mgifford. This PR is ready for review. The only changes are to the pa11y-ci workflow.

Your PRs #123 and #124 should catch some of them. I think the guide sidebar needs ``<li>`` and some other pages might need the change to ``<main>``.

**Review by mgifford — APPROVED** [review]
Only possible issue here is that we should be going with 2.1 if we can. I think that this code does that but the docs don't state it directly.

**Comment by dmundra** [comment]
> Only possible issue here is that we should be going with 2.1 if we can. I think that this code does that but the docs don't state it directly.

I will look into 2.1 and incorporate it.

**Pull request merged**
