### PR TITLE
Updated Pa11y-ci to latest version. Also updated dependencies.

### PR DESCRIPTION
**Pull request by dmundra**
The newest version hopefully has less pa11y-ci run failures. See https://github.com/pa11y/pa11y-ci/issues/128

### CODE REVIEW

**Comment by dmundra** [comment]
Looks like it is failing with a different error. Created https://github.com/pa11y/pa11y-ci/issues/168

**Review by mgifford — DISMISSED** [review]
Good to upgrade...

**Review by mgifford — APPROVED** [review]
Thanks for applying the updates.

**Review by mgifford — APPROVED** [review]
Go 3.0!

**Review by mgifford — APPROVED** [review]
Thanks

**Review by mgifford — APPROVED** [review]
Looks good

**Pull request merged**
