### PR TITLE
Cypress tests

### LINKED ISSUE #409: Feature request: Test accessibility of search form using Cypress
**Is your feature request related to a problem? Please describe.**
Pa11y-ci will test the search page but not the search results as it is dynamic. We might be missing accessibility issues in the search results that we have to check manually.

**For whom is this feature?**
As QA Quincy, I want to test the search form and results automatically, so that I do not have to do it manually.

**Describe the solution you'd like**
Use Cypress and write a test that interacts with the search form and then tests the results for accessibility issues.

**Describe alternatives you've considered**
See if Pa11y-ci could also test the search form after interacting with it.

### PR DESCRIPTION
**Pull request by dmundra**
Closes #409

### CODE REVIEW

**Review by mgifford — APPROVED** [review]
Wait, so Pa11y didn't check the interactive elements? Very much looking forward to learning what cypress-axe catches that pa11y doesn't. Cool comparison.

**Comment by dmundra** [comment]
@mgifford pa11y just runs over the site without interaction. Cypress will allow us to write more interactive tests. I wrote one for the menu and one for the search.

**Review by mgifford — APPROVED** [review]
Looks good. I thought I approved this already.

**Comment by dmundra** [comment]
@mgifford you did. Just making a few more tweaks before I merge it.

**Pull request merged**
