### PR TITLE
Cleaning up and shaping the Onboarding guide

### PR DESCRIPTION
**Pull request by mgifford**
Moving this from the root directory.  I wonder if we can do a redirect from GitHub's code directory...  Probably not.

### CODE REVIEW

**Review by dmundra — CHANGES_REQUESTED** [review]
@mgifford, I think it would be great in the guide but I see this as a new page and not a move of the existing page. What do you think?

Looks you have a few valid typos.

**Comment by dmundra** [comment]
> Moving this from the root directory. I wonder if we can do a redirect from GitHub's code directory... Probably not.

@mgifford, not sure what you mean. We do have the ability to redirect. E.g. https://github.com/CivicActions/accessibility/blob/main/pages/people.html#L5-L6

**Comment by mgifford** [comment]
> @mgifford, I think it would be great in the guide but I see this as a new page and not a move of the existing page. What do you think?

I'm not sure. @lukefretwell was suggesting it should be in the pages folder.  I think you're suggesting something else. 

> Looks you have a few valid typos.

I should fix up the "Hard to read sentence"

Might make sense to go with the american spelling of `centered`

I think this is funny:
    `W3C` is misspelt; did you mean `WC`?                                                                                                                                                                                                                                                                                                                                                                                                                                         
    w3c           retext-spell

Frontend should be Front-end to be more consistent with the web.

So a bit of cleanup still to do.

I don't know what to do with "simple" or "obvious"...

**Comment by dmundra** [comment]
> > @mgifford, I think it would be great in the guide but I see this as a new page and not a move of the existing page. What do you think?
> 
> I'm not sure. @lukefretwell was suggesting it should be in the pages folder. I think you're suggesting something else.
> 
> > Looks you have a few valid typos.
> 
> I should fix up the "Hard to read sentence"
> 
> Might make sense to go with the american spelling of `centered`

Sounds good. I could add the english-gb dictionary but have a follow-up.

> 
> I think this is funny:
> `W3C` is misspelt; did you mean `WC`?
> w3c retext-spell

Maybe we kill retext-spell since it has too many false positives.

> 
> Frontend should be Front-end to be more consistent with the web.

Agreed.

> 
> So a bit of cleanup still to do.
> 
> I don't know what to do with "simple" or "obvious"...

Whatever you recommend.

**Review by dmundra — APPROVED** [review]
Looking good.

**Comment by mgifford** [comment]
> @mgifford, not sure what you mean. We do have the ability to redirect. E.g. https://github.com/CivicActions/accessibility/blob/main/pages/people.html#L5-L6

But we can't redirect a user from https://github.com/CivicActions/accessibility/blob/main/Onboarding.md to https://accessibility.civicactions.com/guide/onboarding

**Comment by dmundra** [comment]
> > @mgifford, not sure what you mean. We do have the ability to redirect. E.g. https://github.com/CivicActions/accessibility/blob/main/pages/people.html#L5-L6
> 
> But we can't redirect a user from https://github.com/CivicActions/accessibility/blob/main/Onboarding.md to https://accessibility.civicactions.com/guide/onboarding

Ah, that is true. Also, we want to add an onboarding link to this page https://github.com/CivicActions/accessibility/tree/main/_guide?

**Pull request merged**
