### PR TITLE
Added cypress-real-events package and tab tests for accordion and menu.

### PR DESCRIPTION
**Pull request by dmundra**
These tests try to mimic keyboard navigation. Needed https://github.com/dmtrKovalenko/cypress-real-events/issues/285 to make it work.

cypress-real-events package: https://github.com/dmtrKovalenko/cypress-real-events

### CODE REVIEW

**Comment by dmundra** [comment]
Related to https://github.com/CivicActions/accessibility/issues/649

**Comment by mgifford** [comment]
Ok, so how do we test it?

**Comment by dmundra** [comment]
> Ok, so how do we test it?

@mgifford you can see the results in two places:

* Summary comment: https://github.com/CivicActions/accessibility/pull/657#issuecomment-1249929456
* Actual one: https://github.com/CivicActions/accessibility/actions/runs/3071258257/jobs/4961779403

**Review by mgifford — APPROVED** [review]
Looks good to me. Happy to see the results of the Cypress tests.

**Pull request merged**
