### PR TITLE
Update designer-darcy.md based on feedback from Ben

### PR DESCRIPTION
**Pull request by mikang**

### CODE REVIEW

**Review by mikang — COMMENTED** [review]
Updated based on the QA tool

**Review by mgifford — COMMENTED** [review]
This looks good. One think I wondered about was consistency with the use of "."'s.  Are we using them or not? Also are we using "-" or "*"?

**Comment by mikang** [comment]
I used "-" and it automatically turned them into the "*" bullet points. I wondered about that, too... I thought it'd be okay to do them just for the ones that have multiple items.

**Comment by mikang** [comment]
@mgifford @dmundra I made edits to designer darcy with * for each point!

**Review by dmundra — APPROVED** [review]
Thanks @mikang

**Pull request merged**
