### PR TITLE
Create /posters folder and add visual impairments poster to it

### PR DESCRIPTION
**Pull request by mikang**
@dmundra what is the best way to make a folder when **uploading** a file? I created a placeholder file to make the folder with a "/" and then deleted it after uploading the poster. Is this the only way?

### CODE REVIEW

**Comment by dmundra** [comment]
@mikang I think what you did was fine but a little bit awkward. I don't have a good answer right now. I think for images we might need to try that. For text files when you create them you can specify a folder in the name of the file.

**Review by dmundra — CHANGES_REQUESTED** [review]
@mikang looks like we have two files. Do you want to delete the older one? Also, you can rename the newer one I think to not have a `(1)` or spaces in it. Easier for the sites to work with.

**Comment by mikang** [comment]
@dmundra interesting, I think it's because GitHub under the hood defines "folders" as just containers for files, so there is no such thing as an empty folder...? https://github.community/t/add-a-folder/2304/6

I think this is true because when I deleted the posters (1).png file, the posters folder disappeared. I've opened the folder again with a ".keep" markdown file. The poster is now renamed and added to the posters folder.

**Comment by dmundra** [comment]
@mikang that makes sense. Good find!

**Review by dmundra — CHANGES_REQUESTED** [review]
@mikang thanks for fixing the file name. I do still see two files when I look at 'Files changed' so I recommend deleting the one from the root of the directory structure. Also since you know have a file in posters the .keep file can be deleted. Thanks

**Comment by mikang** [comment]
I've deleted the two files, @dmundra

**Review by dmundra — APPROVED** [review]

**Pull request merged**
