### PR TITLE
Update persona assets to be the same size

### PR DESCRIPTION
**Pull request by mikang**
The persona images used to have different dimensions. All persona images are now 400x400 px.

### CODE REVIEW

**Comment by mikang** [comment]
@lukefretwell can you please review these images?

**Review by mgifford — APPROVED** [review]
Approved! :)

**Comment by dmundra** [comment]
@mikang you want to merge this and then review on the site?

**Comment by mikang** [comment]
@dmundra done! Sorry, I forgot about merging. Thanks for the follow up.

**Pull request merged**
