### PR TITLE
Mgifford adding anchor links to other pages

### PR DESCRIPTION
**Pull request by mgifford**
pages, blogs, guides & playbooks should all have anchor links associated with the headers.

### CODE REVIEW

**Review by dmundra — CHANGES_REQUESTED** [review]
Testing this locally and I am only seeing giant links i.e. the CSS is not being applied to the guide, playbook pages. Not sure what the restriction is.

CC: @jaube05

**Comment by jaube05** [comment]
@mgifford Still finding the giant links. I added a class "anchor-links" to the personas.html. If you add this class to the div wrapping the main content, on the pages we want, then the styling will take.

**Review by mgifford — COMMENTED** [review]
@dmundra I think this should address the link sizes. Thanks @jaube05 for highlighting what I forgot to bring over.

**Comment by jaube05** [comment]
Sorry one more thing to make it work. This was my fault setting up the styling. 
In _sass/uswds/components/_anchor-links.scss 
remove ".usa-layout-docs.anchor-links" and change to just ".anchor-links". 
Then this PR is good to go!

**Review by jaube05 — APPROVED** [review]

**Comment by mgifford** [comment]
> Sorry one more thing to make it work. This was my fault setting up the styling.
> In _sass/uswds/components/_anchor-links.scss
> remove ".usa-layout-docs.anchor-links" and change to just ".anchor-links".
> Then this PR is good to go!

Ok, I've pulled this in @jaube05 & @dmundra

**Comment by dmundra** [comment]
@mgifford links are looking good. I did notice though the CSS styles to the anchor links did break the news page links.

News page post links screen shot

CC: @jaube05

**Review by dmundra — CHANGES_REQUESTED** [review]
Looking good but maybe needs some CSS triage.

**Comment by mgifford** [comment]
@dmundra can you check it again. I just removed the posts.html change.  I don't think it is critical.

**Review by dmundra — CHANGES_REQUESTED** [review]
@mgifford I tested it and the changes to `_layouts/page.html` is the cause of the issues on news and also the calendar page.

The calendar page issue is that the `h3` is not styled for the anchor links to appear on the left and smaller.

Screenshot of calendar page

**Comment by jaube05** [comment]
@mgifford @dmundra 
Removed the anchor-links class from page.html and adjusting styling of anchor-links on page with sidebar navigvation

**Review by dmundra — CHANGES_REQUESTED** [review]
@jaube05 looks like the calendar page still has giant links. Maybe we revert the changes to `_layouts/page.html`? cc: @mgifford

**Comment by jaube05** [comment]
@mgifford @dmundra  anchor-links should now be working correctly.
Added a new variable anchor-links as front matter, and added code to page.html to check for anchor-links.

**Pull request merged**
